<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>otx</string>
		<string>otool</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^-?\(|^[A]|^\+?\(|^start:|^dyld|^_</string>
	<key>foldingStopMarker</key>
	<string>^\s*$|^\s*\}|^\s*\]|^\s*\)|^\s*"""\s*$</string>
	<key>name</key>
	<string>otool</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(push.|mov..?.?|lea.|and.|j..|cmp.|nop.|xo..|call|pop.|ret.?|j.|test.|movzbl|call.|hlt|shl.|inc.|set..?|orb|cmoveq|dec.|ssb.|pxor|.byte|add.?.?|cvtpi2ps|cvtps2pi|cvtsi2ss|cvtss2si|cvttps2pi|cvttss2si|fstps|sub.?.?|fst|fstcw|fstenv|fstenvw|fstp|fstsw|ftst|fstpl|sar.?|cmov.?.?.?|mul.?.?|or.?.?)\b</string>
			<key>name</key>
			<string>keyword.control.builtin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(BOOL|int|void|long|id|double|const|char|unsigned)</string>
			<key>name</key>
			<string>keyword.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>0x[a-f0-9A-F]{2,16}(\b|\,)</string>
			<key>name</key>
			<string>storage.memorylocation</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(add.|sub.)\b</string>
			<key>name</key>
			<string>keyword.operator.builtin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([A-Fa-f0-9]{16})\b</string>
			<key>name</key>
			<string>constant.numeric.memoryaddress</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(%[A-Z0-9a-z]{2,4})</string>
			<key>name</key>
			<string>constant.language.registers</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+[0-9]{1,}</string>
			<key>name</key>
			<string>keyword.control.linenumber</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(|\)|\[|\]|\-</string>
			<key>name</key>
			<string>variable.paren</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>;</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.semicolon</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.otool.disassembled</string>
	<key>strings</key>
	<dict>
		<key>patterns</key>
		<array>
			<dict>
				<key>begin</key>
				<string>(")</string>
				<key>beginCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.begin.otool</string>
					</dict>
				</dict>
				<key>end</key>
				<string>(")</string>
				<key>endCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.end.otool</string>
					</dict>
				</dict>
				<key>name</key>
				<string>string.quoted.double.otool</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\\.</string>
						<key>name</key>
						<string>constant.character.escape.otool</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>begin</key>
				<string>(')</string>
				<key>beginCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.begin.otool</string>
					</dict>
				</dict>
				<key>end</key>
				<string>(')</string>
				<key>endCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.end.otool</string>
					</dict>
				</dict>
				<key>name</key>
				<string>string.quoted.single.otool</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\\.</string>
						<key>name</key>
						<string>constant.character.escape.otool</string>
					</dict>
				</array>
			</dict>
		</array>
	</dict>
	<key>uuid</key>
	<string>2707A5AB-7677-4DBE-BC9E-6D7DB353E21F</string>
</dict>
</plist>
